version: "3.3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    external_links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: fastify
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"